version: '3.7'
services:
    database:
        image: 'mariadb:11.2.2'
        container_name: 'database'
        restart: unless-stopped
        volumes:
            - ./database:/var/lib/mariaDB
        environment:
            MYSQL_ROOT_PASSWORD: pass4321
            MYSQL_DATABASE: mintos
        ports:
            - '3306'
    phpmyadmin:
        image: 'phpmyadmin:latest'
        container_name: 'phpmyadmin'
        depends_on:
            - database
        ports:
            - 8080:80
        environment:
            PMA_HOST: database